---
# Force CLI for eos_command to ensure running config is returned properly
- name: Gather EOS configuration
  eos_command:
    commands="show running-config all | exclude \.\*"
    provider={{ provider|default(omit) }}
    auth_pass={{ auth_pass|default(omit) }}
    authorize={{ authorize|default(omit) }}
    host={{ host|default(omit) }}
    password={{ password|default(omit) }}
    port={{ port|default(omit) }}
    transport='cli'
    use_ssl={{ use_ssl|default(omit) }}
    username={{ username|default(omit) }}
  register: output
  when: mlag is defined

- set_fact:
    base_config='{{ output.result[0] }}'
  when: mlag is defined

- name: Arista MLAG (Base Configuration)
  eos_template:
    src=base.j2
    include_defaults=True
    config={{ base_config|default(omit) }}
    provider={{ provider|default(omit) }}
    auth_pass={{ auth_pass|default(omit) }}
    authorize={{ authorize|default(omit) }}
    host={{ host|default(omit) }}
    password={{ password|default(omit) }}
    port={{ port|default(omit) }}
    transport={{ transport|default(omit) }}
    use_ssl={{ use_ssl|default(omit) }}
    username={{ username|default(omit) }}
  when: mlag is defined

- name: Arista MLAG (Peer Link Configuration)
  eos_template:
    src=peer_links.j2
    include_defaults=True
    config={{ base_config|default(omit) }}
    provider={{ provider|default(omit) }}
    auth_pass={{ auth_pass|default(omit) }}
    authorize={{ authorize|default(omit) }}
    host={{ host|default(omit) }}
    password={{ password|default(omit) }}
    port={{ port|default(omit) }}
    transport={{ transport|default(omit) }}
    use_ssl={{ use_ssl|default(omit) }}
    username={{ username|default(omit) }}
  with_items: '{{ mlag.peer_link_members | default([]) }}'
  when: mlag is defined
