---
- name: Configure VLAN for MLAG
  eos_vlan:
    vlanid={{ mlag.local_if_vlan | regex_replace('\D+','') }}
    trunk_groups={{ mlag.mlag_trunk_group }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag is defined

- name: Create Vlan Interface for MLAG
  eos_interface:
    name={{ mlag.local_if_vlan|mandatory }}
    description="{{ mlag.local_if_vlan_description|default(mlag.mlag_domain_id) }}"
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag is defined

- name: Configure VLAN Interface IP for MLAG
  eos_ipinterface:
    name={{ mlag.local_if_vlan|mandatory }}
    address={{ mlag.local_if_ip_address|mandatory }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag is defined

- name: Configure Interface Members of Port-Channel for MLAG
  eos_interface:
    name={{ item }}
    description="MLAG Peer  - {{ mlag.mlag_domain_id }}"
    enable={{ mlag.peer_link_enable }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  with_items: mlag.peer_link_members | default([])
  when: mlag.peer_link_members

- name: Configure Interface Members of Port-Channel for MLAG
  eos_portchannel:
    name={{ mlag.peer_link_if }}
    members={{ mlag.peer_link_members | join(',') }}
    lacp_mode={{ mlag.peer_link_lacp_mode|default(active) }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag is defined

- name: Configure switchport mode trunk on Port-Channel
  eos_switchport:
    name={{ mlag.peer_link_if }}
    mode={{ mlag.peer_link_mode }}
    trunk_groups="{{ mlag.mlag_trunk_group|default('trunk') }}"
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag is defined

- name: Configure MLAG
  eos_mlag_config:
    domain_id={{ mlag.mlag_domain_id }}
    local_interface={{ mlag.local_if_vlan }}
    peer_address={{ mlag.peer_address }}
    peer_link={{ mlag.peer_link_if }}
    shutdown={{ mlag.mlag_shutdown }}
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag is defined

- name: Disable Spanning Tree on MLAG Vlan
  eos_config:
    command="no spanning-tree vlan {{ mlag.local_if_vlan | regex_replace('\D+','') }}"
    config={{ eos_eapi_config|default(omit) }}
    username={{ eos_eapi_username|default(omit) }}
    password={{ eos_eapi_password|default(omit) }}
    enablepwd={{ eos_eapi_enablepwd|default(omit) }}
    transport={{ eos_eapi_transport|default(omit) }}
    connection={{ eos_eapi_connection|default(omit) }}
    host={{ eos_eapi_host|default(omit) }}
    port={{ eos_eapi_port|default(omit) }}
    debug={{ eos_debug|default(omit) }}
  when: mlag.local_if_disable_spanning_tree | default(false)
